// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcmqyCothvBDWqu4orNXeFgf6q6Tl-5QQ',
    appId: '1:568615696962:web:24cd196213a09f584ccbdb',
    messagingSenderId: '568615696962',
    projectId: 'expense-tracker-b0776',
    authDomain: 'expense-tracker-b0776.firebaseapp.com',
    storageBucket: 'expense-tracker-b0776.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ZJwNjYuUgcChRnIbQQYK7ZnoVhf-Ngs',
    appId: '1:568615696962:android:d27c3a9b2160aa144ccbdb',
    messagingSenderId: '568615696962',
    projectId: 'expense-tracker-b0776',
    storageBucket: 'expense-tracker-b0776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeuGEglq_2douUVx8WWMc1YFl4Z6t6VXA',
    appId: '1:568615696962:ios:9d849602ebfa02cf4ccbdb',
    messagingSenderId: '568615696962',
    projectId: 'expense-tracker-b0776',
    storageBucket: 'expense-tracker-b0776.appspot.com',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeuGEglq_2douUVx8WWMc1YFl4Z6t6VXA',
    appId: '1:568615696962:ios:9d849602ebfa02cf4ccbdb',
    messagingSenderId: '568615696962',
    projectId: 'expense-tracker-b0776',
    storageBucket: 'expense-tracker-b0776.appspot.com',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcmqyCothvBDWqu4orNXeFgf6q6Tl-5QQ',
    appId: '1:568615696962:web:cffd1c9db035e7d44ccbdb',
    messagingSenderId: '568615696962',
    projectId: 'expense-tracker-b0776',
    authDomain: 'expense-tracker-b0776.firebaseapp.com',
    storageBucket: 'expense-tracker-b0776.appspot.com',
  );
}
